### ISSUE TITLE
Navbar doesn't keeps the box shadow while closed

### ISSUE THREAD

**Issue by felipebruce** [Jordan-Hall/angular-material-rail-drawer-plugin#10]
If I use a box-shadow, the side-nav (`mode="rail"`), keeps it only when opened. When I close, the box-shadow disapear.

**Comment by Jordan-Hall** [comment]
Hi @felipebruce have you got an example app?

**Comment by felipebruce** [comment]
Oh, my bad. I forgot to put in here.
 
It happens either on https://stackblitz.com/edit/angular-material-mini-variant or in my own project. I just added a class called "test": 
`<mat-sidenav #appDrawer mode="rail" opened="true" (openedChange)="openedChange(appDrawer.opened)" class="test">`.

That's the app.component.scss: 
`.container {
    padding: 8px 24px 108px 24px;
}`
`.test {
  box-shadow: 2px 1px black;
}`

All the code above was done at https://stackblitz.com/edit/angular-material-mini-variant.

**Comment by Jordan-Hall** [comment]
I believe this is related to the animation. You will have to override the animation example.

Issue closed please read https://github.com/Jordan-Hall/angular-material-rail-drawer-plugin/issues/56
