### ISSUE TITLE
Upgrading to Angular 10 gives dependency error 

### ISSUE THREAD

**Issue by Hyperionza** [Jordan-Hall/angular-material-rail-drawer-plugin#24]
Hi there,

1st - Thank you! Its amazing that the Angular Material team don't have this in their original control. I would have thought it was a common use case.

2nd - I just upgraded from Angular 9.1.5 to v10 (which was only released yesterday) and when doing the Material part of the upgrade, it rejects it with a dependency error as you've marked your plugin to use < 10.0.0. I used the --forced option to complete the upgrade and the control still works. Granted I've only been testing in Chrome so far. Just checked the Angular Material documentation and it still does not make mention of mode="rail" as one of the options. So I think its safe for you to raise the dependency version to allow the upgrade without using --forced.

**Comment by Jordan-Hall** [comment]
I'm taking a look at Angular 10 upgrade this weekend. Please bare with me

**Comment by KestrelKitezh** [comment]
Same goes for v11. Works fine so far. Love the rail, thanks dude <3

**Comment by Jordan-Hall** [comment]
@Hyperionza  @KestrelKitezh  this should now be resolved thanks to someone's contribution to migrate to latest version
