### ISSUE TITLE
Mode does not work for property binding values

### ISSUE THREAD

**Issue by AmandavZ** [Jordan-Hall/angular-material-rail-drawer-plugin#25]
Hi Jordan. 

Thank you for the plugin and for sharing is with the community! 

I would like to make the mode conditional (based on media queries) but as soon as I change the mode to a property binding value, it defaults to 'over'. 

```
<mat-sidenav #appDrawer [mode]="mode" opened="true">

import { Component, ViewChild, ElementRef } from '@angular/core';

@Component()
export class AppComponent {
  mode = 'rail';
} 
```

Please can you point me in the right direction?
Thanking you
Amanda

**Comment by Jordan-Hall** [comment]
Apologies for the delay, Will address this issue tomorrow for you. Hoping to get a first major release out on sunday

**Comment by mcurrycl** [comment]
Sorry to hassle you, is there any solution to this?

**Comment by mvmjacobs** [comment]
Hi @Jordan-Hall
Is there any update about this issue?

Thanks!

**Comment by yalamber** [comment]
seems like this is still not supported

**Comment by Jordan-Hall** [comment]
Hey, been really busy and not taken a look. I'll have a look at the weekend

**Comment by Ben0421** [comment]
This would be very useful for projects with strict type checking in template:
> Type '"rail"' is not assignable to type 'MatDrawerMode'.ngtsc(2322)

Using [mode]="var" would allow us to typecast rail to any.

**Comment by Jordan-Hall** [comment]
Issue closed please read https://github.com/Jordan-Hall/angular-material-rail-drawer-plugin/issues/56
