### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by uahic** [Jordan-Hall/angular-material-rail-drawer-plugin#29]
Hi there, Im currently checking out your package, great work! thank you very much!

One thing that is missing is a license (at least on npm) (hopefully like MIT or BSD,...  :) ) such that I am allowed to use it for commercial applications

**Comment by Jordan-Hall** [comment]
I believe in open source. ZERO license, you can do anything you like with the code 👍

**Comment by Jordan-Hall** [comment]
https://github.com/Jordan-Hall/angular-material-rail-drawer-plugin/blob/master/license

Enjoy
