### ISSUE TITLE
Accidentally removed module from public_api.ts

### ISSUE THREAD

**Issue by Braincompiler** [Jordan-Hall/angular-material-rail-drawer-plugin#49]
It seems you removed the module from the public_api.ts accidentally: https://github.com/Jordan-Hall/angular-material-rail-drawer-plugin/commit/dd64664da05004e20d2bdfe71091b5b518835af7#diff-13acfda7a5a5e239d77d61503fc8655d27bba738385a9ff459bd25025bfbe860

I just updated to the latest version and my build broke. I found out there the DrawerRailModule is missed. After a short research I found the mistake. I also created a PR to fix this.

**Comment by Jordan-Hall** [comment]
Done a release. Thank you so much, I dont personally use this anymore, and I was seeing about standalone version hence it was removed by mistake
