### ISSUE TITLE
Angular 16 Support

### ISSUE THREAD

**Issue by SandeepThomas** [Jordan-Hall/angular-material-rail-drawer-plugin#54]
Any plans to support angular 16?

**Comment by SandeepThomas** [comment]
@Jordan-Hall I have added PR to address this: https://github.com/Jordan-Hall/angular-material-rail-drawer-plugin/pull/55, could you please review?

**Comment by SandeepThomas** [comment]
Hi @Jordan-Hall, waiting for the new release, any eta on when it would be done?

**Comment by Jordan-Hall** [comment]
Sorry I'll do it now. I've been working in something for last few days so I forgot to get around to the release

**Comment by Jordan-Hall** [comment]
Released. Thank you agaain
