### ISSUE TITLE
Support for position="end" on <mat-sidenav>

### ISSUE THREAD

**Issue by robertgartman** [Jordan-Hall/angular-material-rail-drawer-plugin#6]
Thanks for this great contribution. Any plans on supporting right side drawer?

The current issue (version 0.0.4) can be reproduced by adding `position="end"` on your [Stackblitz](https://stackblitz.com/edit/angular-material-mini-variant) and toggle the drawer. The main content moves sideways.

**Comment by Jordan-Hall** [comment]
Hey, ill take a look and aim to add support. Hopefully it's added today or tomorrow

**Comment by Jordan-Hall** [comment]
@robertgartman  apologies for delay, I replied early hours of this morning so you knew it was going to be looked into. The issue is now resolved https://github.com/Jordan-Hall/angular-material-rail-drawer-plugin/pull/7

Can you please reply to confirm this issue has now been resolved.

**Comment by robertgartman** [comment]
Version 0.0.5 resolves the issue. Much appreciated!
