### ISSUE TITLE
Current mode (mini/expanded) API variable

### ISSUE THREAD

**Issue by enlight3d** [Jordan-Hall/angular-material-rail-drawer-plugin#8]
Hello, is there any API variable that can tell programatically if the drawer is in mini or expanded mode ?
I've seen that you've added APIs that I were searching for yesterday so maybe you have this one too ?

**Comment by Jordan-Hall** [comment]
Hi @enlight3d,

This supports all of Angular Material native API https://material.angular.io/components/sidenav/api#MatDrawer So you can even use the output event or use the opened property

one example to show both:
``` <mat-sidenav #appDrawer mode="rail" opened="true" (openedChange)="openedChange(appDrawer.opened)">```

**Comment by Jordan-Hall** [comment]
I've just updated the read me to include a link to Angular Material API properties as we do not effect the underlying functionality.

close === mini
opened === expanded

**Comment by enlight3d** [comment]
Thanks a lot for this explanation. Was concerned that close could have been just "closed" because last time when I put "opened=false" thinking it would start in mini mode and not expanded, the sidebar just didn't appear at all.

**Comment by Jordan-Hall** [comment]
Thakn you

**Comment by Jordan-Hall** [comment]
Thank you for raising the opened=false bug. Will look into it shortly.

**Comment by enlight3d** [comment]
you're welcome

**Comment by Jordan-Hall** [comment]
Fixed in version 0.0.6. Think i'll be making it a solid version in the next couple of weeks

https://github.com/Jordan-Hall/angular-material-rail-drawer-plugin/pull/9

**Comment by enlight3d** [comment]
Great ! Thank you
